/* ***************************************************************************
 * Copyright 2019 Geeks18, Inc.  All rights reserved.
 * -- Geeks18 Confidential
 * ***************************************************************************
 * $Author$ $Id$ $DateTime$
 * ***************************************************************************/

package com.test.dynamo.geeks18.repository;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/** 
 * <code>RequestDto</code> is the DTO for request <br>
 *
 * @version <1.0> 
 * @author dmahapatra
 */
@DynamoDBTable(tableName="geeks18_table")
public class RequestDto {
    @Id
    private RequestId id;
    
    @DynamoDBHashKey(attributeName = "req_id")
    private String reqId;
    
    @DynamoDBRangeKey(attributeName = "req_name")
    private String regName;
    
    @DynamoDBAttribute(attributeName = "prod_name")
    private String name;
    
    @DynamoDBAttribute(attributeName = "data_test")
    private String testData;
    
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute(attributeName = "created_date")
    private String createdDate;
    
    public String getReqId() {
        return reqId;
    }
    public void setReqId(String reqId) {
        this.reqId = reqId;
    }
    public String getRegName() {
        return regName;
    }
    public void setRegName(String regName) {
        this.regName = regName;
    }
    public String getCreatedDate() {
        return createdDate;
    }
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }
    public RequestId getId() {
        return id;
    }
    public void setId(RequestId id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getTestData() {
        return testData;
    }
    public void setTestData(String testData) {
        this.testData = testData;
    }
}
